### PR TITLE
Various changes for Darwin - macOS build.

### PR DESCRIPTION
**Pull request by Blady-Com**
Various changes for Darwin - macOS build.
PATH=/usr/local/xnadalib-2016/bin:$PATH ./configure --prefix=build --without-bdb --without-mysql --without-opengl --without-postgres --without-readline --without-sound --arch=native

### CODE REVIEW

**Comment by kburtch** [comment]
Merge still to be tested on other architectures.

**Comment by kburtch** [comment]
The configure script SDL test seems to be failing on the continuous integration server which is running CentOS 7.

**Comment by kburtch** [comment]
Fixed.

**Comment by Blady-Com** [comment]
Hello Ken,
Many thanks for taking in account various changes to build SparForte on macOS.
I tried to minimized the impact for other systems.
Seem not the case for CentOS.
Unfortunately your last revert on configure file has cancel many needed changes.

Thus now it fails:

./configure --prefix=build --without-bdb --without-mysql --without-opengl --without-postgres --without-readline --without-sound --arch=native
fgrep: /etc/issue: No such file or directory
fgrep: /etc/issue: No such file or directory
Configuring SparForte...
checking for pkg_config... yes
checking for locate (glocate)... no
checking for locate (locate)... yes
checking for OS (uname -s)... yes
checking for architecture ($ARCH)... yes
making for... unknown
I couldn't identify your operating system.
SparForte requires a spar_os.ads file to make operating system calls.
If I made a mistake and your O/S is supported, manually copy
a spar_* file to spar_os.  If you're operating system isn't supported
and if you are experienced and have time, you can create a new
spar_os.ads for your operating system.  Consult the Hacker's Guide
in the documentation on how to port SparForte to a new operating system.

What do you think the best to do?
Regards, Pascal.

**Comment by kburtch** [comment]
Committed wrong file.  Try this one.

**Comment by Blady-Com** [comment]
Hello Ken,
It's ok for me now, thanks a lot.
I'm very impressed by the online version: http://sparforte.com/repl.sp
I haven't found it in SparForte examples.
Where repl.sp AdaScript can be found?

How can I contact (otherwise by github)?
I see "Contact information is located on the PegaSoft People Page."
But http://www.pegasoft.ca/people.html gives "The requested URL /people.html was not found on this server."

Regards, Pascal.

**Comment by kburtch** [comment]
Write me at ken at pegasoft.ca.  I am also on LinkedIn.

**Comment by kburtch** [comment]
I haven't published repl.sp but I can email it to you.
I will update the people link when I get a chance.
I may also setup a sparforte mailing list.  There was a request for one a few months ago.

**Pull request merged**
